# pull official base image
FROM node:13.12.0-alpine AS builder

# set working directory
WORKDIR /usr/src/app

# install app dependencies
COPY ./package.json ./
COPY ./package-lock.json ./

RUN npm install 

# add app
COPY . .

RUN npm run build

### second stage
FROM caddy:2.1.1

ARG CADDYFILE
COPY ${CADDYFILE} /etc/caddy/Caddyfile

COPY --from=builder /usr/src/app/build/ /srv

EXPOSE 80

EXPOSE 443