// Authentication
export const USER_SIGN_ON = 'USER_LOGGED_IN';
export const USER_SIGN_OFF = 'USER_SIGN_OFF';

// User
export const USER_LOGGED_FOOD = 'USER_LOGGED_FOOD';
export const UPDATED_USER_PROFILE = 'UPDATED_USER_PROFILE';
export const USER_PROFILE_FETCHED = 'USER_PROFILE_FETCHED';


// Nutritionix Search
export const SEARCH_COMPLETE = 'SEARCH_COMPLETE';
export const SEARCH_ITEM_SELECTED = 'SEARCH_ITEM_SELECTED';
export const SEARCH_ITEM_DESELECTED = 'SEARCH_ITEM_DESELECTED';

// Food
export const LOG_ITEM_REMOVED = 'LOG_ITEM_REMOVED';

// Exercise
export const EXERCISE_LOG_ADDED = 'EXERCISE_LOG_ADDED';
export const EXERCISE_LOGS_FETCHED = 'EXERCISE_LOGS_FETCHED';
export const EXERCISE_LOG_REMOVED = 'EXERCISE_LOG_REMOVED';