export const USER_SIGN_ON = 'USER_LOGGED_IN';
export const USER_SIGN_OFF = 'USER_SIGN_OFF';
export const USER_LOGS_FETCHED = 'USER_INFO_FETCH';
export const USER_LOGGED_FOOD = 'USER_LOGGED_FOOD';

export const SEARCH_COMPLETE = 'SEARCH_COMPLETE';

